# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'translo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for translo

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React', path: '../node_modules/react-native'
  pod 'TwilioVideo'

end
